// This file is auto-generated by Supabase CLI: supabase gen types typescript
// For now, we'll use a basic type structure. You can regenerate this after running
// the Supabase CLI: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          role: 'camper' | 'farmer' | 'admin';
          farm_name: string | null;
          farm_address: string | null;
          postcode: string | null;
          county: string | null;
          subscription_status: string;
          subscription_type: string | null;
          subscription_start_date: string | null;
          subscription_end_date: string | null;
          verified: boolean;
          join_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at' | 'join_date'> & {
          created_at?: string;
          updated_at?: string;
          join_date?: string;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      listings: {
        Row: {
          id: string;
          farmer_id: string;
          title: string;
          description: string;
          location: string;
          address: string | null;
          postcode: string | null;
          county: string | null;
          latitude: number | null;
          longitude: number | null;
          price: number;
          price_per_night: number | null;
          max_guests: number;
          amenities: string[];
          restrictions: string[];
          seasonal_highlights: string[];
          images: string[];
          parking_location: string | null;
          cancellation_policy: string | null;
          availability: 'available' | 'pending' | 'suspended';
          rating: number | null;
          wildness_rating: number | null;
          review_count: number;
          status: 'pending' | 'approved' | 'rejected' | 'live';
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['listings']['Row'], 'id' | 'created_at' | 'updated_at' | 'review_count'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
          review_count?: number;
        };
        Update: Partial<Database['public']['Tables']['listings']['Insert']>;
      };
      bookings: {
        Row: {
          id: string;
          listing_id: string;
          listing_title: string;
          camper_id: string;
          camper_name: string;
          farmer_id: string;
          start_date: string;
          end_date: string;
          total_price: number;
          guests: number;
          special_requests: string | null;
          status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'upcoming';
          waiver_accepted: boolean;
          waiver_type: string | null;
          waiver_accepted_at: string | null;
          waiver_text_snapshot: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['bookings']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['bookings']['Insert']>;
      };
      reviews: {
        Row: {
          id: string;
          listing_id: string;
          reviewer_id: string;
          booking_id: string | null;
          rating: number;
          title: string | null;
          comment: string | null;
          approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>;
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          receiver_id: string;
          listing_id: string | null;
          message_text: string;
          read: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['messages']['Insert']>;
      };
      favorites: {
        Row: {
          id: string;
          camper_id: string;
          listing_id: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['favorites']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['favorites']['Insert']>;
      };
      farmer_ratings: {
        Row: {
          id: string;
          farmer_id: string;
          reviewer_id: string;
          rating: number;
          comment: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['farmer_ratings']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['farmer_ratings']['Insert']>;
      };
      support_tickets: {
        Row: {
          id: string;
          user_id: string | null;
          name: string | null;
          email: string | null;
          subject: string;
          message: string;
          status: 'open' | 'in_progress' | 'resolved' | 'closed';
          assigned_to: string | null;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['support_tickets']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['support_tickets']['Insert']>;
      };
    };
  };
}


