// Mock data for local testing - matches original project
export const MOCK_DATA = {
  users: [
    {
      id: '1',
      email: 'camper@test.com',
      password: 'password123',
      firstName: 'John',
      lastName: 'Camper',
      role: 'camper',
      phone: '+1234567890',
      verified: true,
      subscriptionStatus: 'active',
      subscriptionType: 'monthly',
      subscriptionStartDate: '2024-01-15',
      subscriptionEndDate: '2026-01-15',
      subscriptionRenewalDate: '2026-01-15',
      joinDate: '2024-01-15',
    },
    {
      id: '2',
      email: 'farmer@test.com',
      password: 'password123',
      firstName: 'Sarah',
      lastName: 'Farmer',
      role: 'farmer',
      phone: '+1234567891',
      verified: true,
      subscriptionStatus: 'active',
      joinDate: '2024-01-10',
    },
    {
      id: '3',
      email: 'expired@test.com',
      password: 'password123',
      firstName: 'Jane',
      lastName: 'Expired',
      role: 'camper',
      phone: '+1234567892',
      verified: true,
      subscriptionStatus: 'expired',
      subscriptionType: 'monthly',
      subscriptionStartDate: '2023-12-01',
      subscriptionEndDate: '2024-01-01',
      subscriptionRenewalDate: '2024-01-01',
      joinDate: '2023-12-01',
    },
  ],
  listings: [
    {
      id: '1',
      farmerId: '2',
      title: 'Antrim Hill Farm',
      description: 'A stunning farm overlooking the Antrim coast with breathtaking sea views. Perfect for wild camping with access to ancient landmarks.',
      location: 'Ballycastle, Northern Ireland',
      address: '12 Castle Road',
      postcode: 'BT54 6LW',
      latitude: 55.2044,
      longitude: -6.2586,
      price: 28,
      pricePerNight: 28,
      maxGuests: 4,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'WiFi', 'Water Supply', 'Coastal Access'],
      images: ['https://example.com/farm1.jpg'],
      availability: 'available',
      rating: 4.8,
      wildnessRating: 4,
      reviewCount: 15,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    {
      id: '2',
      farmerId: '2',
      title: 'Belfast Valley Farm',
      description: 'Peaceful rural farm in the Belfast hills with rolling fields and fresh mountain air. Close to city yet completely secluded.',
      location: 'Belfast, Northern Ireland',
      address: '45 Mountain View Lane',
      postcode: 'BT17 0RJ',
      latitude: 54.5781,
      longitude: -6.0000,
      price: 32,
      pricePerNight: 32,
      maxGuests: 6,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'WiFi', 'Walking Trails', 'Mountain Views'],
      images: ['https://example.com/farm2.jpg'],
      availability: 'available',
      rating: 4.9,
      wildnessRating: 3,
      reviewCount: 22,
      createdAt: '2024-01-12T14:00:00Z',
      updatedAt: '2024-01-12T14:00:00Z',
    },
    {
      id: '3',
      farmerId: '2',
      title: 'Causeway Coast Farm',
      description: 'Unique wild camping experience near the Giant\'s Causeway. Explore ancient rock formations and stunning coastal cliffs.',
      location: 'Coleraine, Northern Ireland',
      address: '8 Causeway Road',
      postcode: 'BT52 2PJ',
      latitude: 55.2411,
      longitude: -6.5117,
      price: 35,
      pricePerNight: 35,
      maxGuests: 4,
      amenities: ['Parking', 'Compost Toilets', 'Fire Pit', 'BBQ', 'Wildlife Watching', 'Cliff Access', 'Heritage Site'],
      images: ['https://example.com/farm3.jpg'],
      availability: 'available',
      rating: 4.7,
      wildnessRating: 5,
      reviewCount: 18,
      createdAt: '2024-01-15T09:00:00Z',
      updatedAt: '2024-01-15T09:00:00Z',
    },
    {
      id: '4',
      farmerId: '2',
      title: 'Fermanagh Lake Farm',
      description: 'Secluded lake-side camping with pristine views and abundant wildlife. Perfect for fishing, kayaking, and bird watching.',
      location: 'Enniskillen, Northern Ireland',
      address: '23 Lough Shore Road',
      postcode: 'BT92 9BP',
      latitude: 54.3464,
      longitude: -7.6456,
      price: 30,
      pricePerNight: 30,
      maxGuests: 5,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'Lake Access', 'Kayaking', 'Fishing', 'Bird Watching'],
      images: ['https://example.com/farm4.jpg'],
      availability: 'available',
      rating: 4.9,
      wildnessRating: 4,
      reviewCount: 25,
      createdAt: '2024-01-18T11:00:00Z',
      updatedAt: '2024-01-18T11:00:00Z',
    },
    {
      id: '5',
      farmerId: '2',
      title: 'Mourne Mountains Farm',
      description: 'High altitude farm with panoramic mountain views. Experience the wild Irish countryside with access to the Mourne Mountains.',
      location: 'Newry, Northern Ireland',
      address: '56 Mountain Trail',
      postcode: 'BT34 3NW',
      latitude: 54.1781,
      longitude: -6.0615,
      price: 38,
      pricePerNight: 38,
      maxGuests: 3,
      amenities: ['Parking', 'Compost Toilets', 'Fire Pit', 'BBQ', 'Mountain Views', 'Hiking Access', 'Stargazing', 'Wild Meadows'],
      images: ['https://example.com/farm5.jpg'],
      availability: 'available',
      rating: 4.8,
      wildnessRating: 5,
      reviewCount: 30,
      createdAt: '2024-01-20T15:00:00Z',
      updatedAt: '2024-01-20T15:00:00Z',
    },
    {
      id: '6',
      farmerId: '2',
      title: 'Cliffs of Moher Farm',
      description: 'Dramatic coastal camping with panoramic views of the Atlantic Ocean. Close to the famous Cliffs of Moher and Burren National Park.',
      location: 'Liscannor, County Clare, Ireland',
      address: '67 Atlantic View Road',
      postcode: 'V95 K8N6',
      latitude: 52.9714,
      longitude: -9.4260,
      price: 40,
      pricePerNight: 40,
      maxGuests: 4,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'Coastal Access', 'Cliff Views', 'Wildlife Watching', 'Stargazing'],
      images: ['https://example.com/farm6.jpg'],
      availability: 'available',
      rating: 4.9,
      wildnessRating: 5,
      reviewCount: 28,
      createdAt: '2024-01-22T10:00:00Z',
      updatedAt: '2024-01-22T10:00:00Z',
    },
    {
      id: '7',
      farmerId: '2',
      title: 'Kerry Mountain Farm',
      description: 'Remote mountain farm in the heart of Kerry with stunning views of the Ring of Kerry. Perfect for hiking enthusiasts.',
      location: 'Killarney, County Kerry, Ireland',
      address: '34 Mountain Pass',
      postcode: 'V93 YK67',
      latitude: 52.0597,
      longitude: -9.5083,
      price: 35,
      pricePerNight: 35,
      maxGuests: 5,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'Mountain Views', 'Hiking Trails', 'Lakes', 'Ancient Sites'],
      images: ['https://example.com/farm7.jpg'],
      availability: 'available',
      rating: 4.7,
      wildnessRating: 5,
      reviewCount: 20,
      createdAt: '2024-01-24T14:00:00Z',
      updatedAt: '2024-01-24T14:00:00Z',
    },
    {
      id: '8',
      farmerId: '2',
      title: 'Wild Atlantic Farm',
      description: 'Secluded coastal farm on the stunning Wild Atlantic Way. Experience rugged coastline, pristine beaches, and magnificent sunsets.',
      location: 'Dingle, County Kerry, Ireland',
      address: '89 Wild Coast Road',
      postcode: 'V92 YR86',
      latitude: 52.1413,
      longitude: -10.2709,
      price: 42,
      pricePerNight: 42,
      maxGuests: 3,
      amenities: ['Parking', 'Compost Toilets', 'Fire Pit', 'BBQ', 'Beach Access', 'Wildlife Watching', 'Dolphin Spotting', 'Island Tours'],
      images: ['https://example.com/farm8.jpg'],
      availability: 'available',
      rating: 4.8,
      wildnessRating: 4,
      reviewCount: 32,
      createdAt: '2024-01-26T09:00:00Z',
      updatedAt: '2024-01-26T09:00:00Z',
    },
    {
      id: '9',
      farmerId: '2',
      title: 'Wicklow Mountains Farm',
      description: 'Serene farm in the Wicklow Mountains overlooking Dublin Bay. Explore ancient forests, mountain streams, and heritage sites.',
      location: 'Wicklow, County Wicklow, Ireland',
      address: '12 Heritage Valley Lane',
      postcode: 'A67 TK88',
      latitude: 53.0100,
      longitude: -6.0431,
      price: 33,
      pricePerNight: 33,
      maxGuests: 6,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'WiFi', 'Mountain Views', 'Forest Walks', 'Historical Sites'],
      images: ['https://example.com/farm9.jpg'],
      availability: 'available',
      rating: 4.9,
      wildnessRating: 3,
      reviewCount: 35,
      createdAt: '2024-01-28T12:00:00Z',
      updatedAt: '2024-01-28T12:00:00Z',
    },
    {
      id: '10',
      farmerId: '2',
      title: 'Connemara Wild Farm',
      description: 'Authentic Irish farming experience in the untamed Connemara region. Surrounded by mountains, lakes, and wild Atlantic scenery.',
      location: 'Clifden, County Galway, Ireland',
      address: '45 Connemara Way',
      postcode: 'H71 EK92',
      latitude: 53.4870,
      longitude: -10.0460,
      price: 36,
      pricePerNight: 36,
      maxGuests: 4,
      amenities: ['Parking', 'Toilets', 'Shower', 'Fire Pit', 'BBQ', 'Lakes', 'Mountain Views', 'Authentic Farm Experience', 'Horse Riding'],
      images: ['https://example.com/farm10.jpg'],
      availability: 'available',
      rating: 4.6,
      wildnessRating: 4,
      reviewCount: 18,
      createdAt: '2024-01-30T16:00:00Z',
      updatedAt: '2024-01-30T16:00:00Z',
    },
  ],
  bookings: [
    {
      id: '1',
      listingId: '1',
      listingTitle: 'Antrim Hill Farm',
      camperId: '1',
      camperName: 'John Camper',
      farmerId: '2',
      startDate: '2024-11-20',
      endDate: '2024-11-22',
      totalPrice: 56.00,
      status: 'confirmed',
      createdAt: '2024-10-01T10:00:00Z',
      updatedAt: '2024-10-01T10:00:00Z',
    },
    {
      id: '2',
      listingId: '2',
      listingTitle: 'Belfast Valley Farm',
      camperId: '1',
      camperName: 'John Camper',
      farmerId: '2',
      startDate: '2024-10-01',
      endDate: '2024-10-03',
      totalPrice: 64.00,
      status: 'completed',
      createdAt: '2024-09-15T14:00:00Z',
      updatedAt: '2024-10-03T12:00:00Z',
    },
    {
      id: '3',
      listingId: '3',
      listingTitle: 'Causeway Coast Farm',
      camperId: '1',
      camperName: 'John Camper',
      farmerId: '2',
      startDate: '2024-12-15',
      endDate: '2024-12-17',
      totalPrice: 70.00,
      status: 'pending',
      createdAt: '2024-10-10T16:00:00Z',
      updatedAt: '2024-10-10T16:00:00Z',
    },
  ],
  reviews: [
    {
      id: '1',
      listingId: '1',
      reviewerId: '1',
      reviewerName: 'John Camper',
      rating: 5,
      comment: 'Amazing farm with beautiful views! The farmer was very welcoming and the facilities were clean.',
      createdAt: '2024-10-05T10:00:00Z',
      updatedAt: '2024-10-05T10:00:00Z',
    },
    {
      id: '2',
      listingId: '2',
      reviewerId: '1',
      reviewerName: 'John Camper',
      rating: 4,
      comment: 'Great location and peaceful atmosphere. The sunset views were incredible!',
      createdAt: '2024-10-04T15:00:00Z',
      updatedAt: '2024-10-04T15:00:00Z',
    },
  ],
  messages: [
    {
      id: '1',
      conversationId: '1-2',
      senderId: '1',
      senderName: 'John Camper',
      receiverId: '2',
      content: 'Hi, I\'m interested in your farm for next weekend. Is it available?',
      timestamp: '2024-10-14T10:00:00Z',
      read: false,
    },
    {
      id: '2',
      conversationId: '1-2',
      senderId: '2',
      senderName: 'Sarah Farmer',
      receiverId: '1',
      content: 'Yes, it\'s available! I\'d be happy to host you.',
      timestamp: '2024-10-14T10:30:00Z',
      read: true,
    },
  ],
  favorites: [
    {
      id: '1',
      userId: '1',
      listingId: '1',
      farmName: 'Green Valley Farm',
      location: 'Yorkshire, UK',
      price: 25,
      rating: 4.8,
      addedDate: '2024-01-20T16:00:00Z',
    },
    {
      id: '2',
      userId: '1',
      listingId: '2',
      farmName: 'Sunset Meadows',
      location: 'Devon, UK',
      price: 30,
      rating: 4.9,
      addedDate: '2024-01-25T12:00:00Z',
    },
  ],
  farmerRatings: [
    {
      id: '1',
      farmerId: '2',
      camperId: '1',
      rating: 5,
      comment: 'Sarah is a wonderful host! Very welcoming and helpful.',
      createdAt: '2024-10-05T10:00:00Z',
    },
  ],
};

// Storage keys
const STORAGE_KEYS = {
  USERS: 'wildstay_users',
  LISTINGS: 'wildstay_listings',
  BOOKINGS: 'wildstay_bookings',
  REVIEWS: 'wildstay_reviews',
  MESSAGES: 'wildstay_messages',
  FAVORITES: 'wildstay_favorites',
  FARMERRATINGS: 'wildstay_farmer_ratings',
  CURRENT_USER: 'wildstay_current_user',
};

// Initialize local storage with mock data
export const initializeLocalStorage = () => {
  try {
    // Check if data already exists
    const existingUsers = localStorage.getItem(STORAGE_KEYS.USERS);
    if (!existingUsers) {
      // Store mock data
      localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(MOCK_DATA.users));
      localStorage.setItem(STORAGE_KEYS.LISTINGS, JSON.stringify(MOCK_DATA.listings));
      localStorage.setItem(STORAGE_KEYS.BOOKINGS, JSON.stringify(MOCK_DATA.bookings));
      localStorage.setItem(STORAGE_KEYS.REVIEWS, JSON.stringify(MOCK_DATA.reviews));
      localStorage.setItem(STORAGE_KEYS.MESSAGES, JSON.stringify(MOCK_DATA.messages));
      localStorage.setItem(STORAGE_KEYS.FAVORITES, JSON.stringify(MOCK_DATA.favorites));
      localStorage.setItem(STORAGE_KEYS.FARMERRATINGS, JSON.stringify(MOCK_DATA.farmerRatings));
      console.log('✅ Mock data initialized in local storage');
    }
  } catch (error) {
    console.error('Error initializing mock data:', error);
  }
};

// Force reinitialize local storage with updated mock data
export const forceReinitializeLocalStorage = () => {
  try {
    console.log('🔄 Force reinitializing local storage with updated mock data...');
    
    // Clear all existing data
    localStorage.removeItem(STORAGE_KEYS.USERS);
    localStorage.removeItem(STORAGE_KEYS.LISTINGS);
    localStorage.removeItem(STORAGE_KEYS.BOOKINGS);
    localStorage.removeItem(STORAGE_KEYS.REVIEWS);
    localStorage.removeItem(STORAGE_KEYS.MESSAGES);
    localStorage.removeItem(STORAGE_KEYS.FAVORITES);
    localStorage.removeItem(STORAGE_KEYS.FARMERRATINGS);
    localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);
    
    // Store updated mock data
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(MOCK_DATA.users));
    localStorage.setItem(STORAGE_KEYS.LISTINGS, JSON.stringify(MOCK_DATA.listings));
    localStorage.setItem(STORAGE_KEYS.BOOKINGS, JSON.stringify(MOCK_DATA.bookings));
    localStorage.setItem(STORAGE_KEYS.REVIEWS, JSON.stringify(MOCK_DATA.reviews));
    localStorage.setItem(STORAGE_KEYS.MESSAGES, JSON.stringify(MOCK_DATA.messages));
    localStorage.setItem(STORAGE_KEYS.FAVORITES, JSON.stringify(MOCK_DATA.favorites));
    localStorage.setItem(STORAGE_KEYS.FARMERRATINGS, JSON.stringify(MOCK_DATA.farmerRatings));
    
    console.log('✅ Local storage force reinitialized successfully');
  } catch (error) {
    console.error('Error force reinitializing mock data:', error);
  }
};
